### ISSUE TITLE
E492: Not an editor command: import vim

### ISSUE THREAD

**Issue by svenfraeys** [yamahigashi/sendtomaya.vim#1]
Hello,
I installed it with vundle.
But when running the command I get following error :

Error detected while processing function send_to_maya#send..<SNR>94_do_send:
line    3:
E492: Not an editor command: import vim

**Comment by yamahigashi** [comment]
try this: https://github.com/VundleVim/Vundle.vim/wiki/Common-Issues

**Comment by yamahigashi** [comment]
Or check your vim was compiled with python

```vim
:version
```
